# Generated by Django 4.1.5 on 2023-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_description_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
