# Generated by Django 4.1.5 on 2023-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_address_remove_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('alley', models.CharField(max_length=200)),
                ('plaque', models.CharField(max_length=200)),
                ('postalـcode', models.CharField(max_length=200)),
            ],
        ),
    ]
