# Generated by Django 4.1.5 on 2023-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='extra_commnent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
